name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2


    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Pull Docker Image from Docker Hub
      run: |
        docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-fastapi-app:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Deploy to Azure Web Apps
      id: deploy-to-webapp
      uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
      with:
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: ${{ secrets.DOCKER_HUB_USERNAME }}/my-fastapi-app:latest
        resource-group: 'dsMidterm'
        app-name: 'MidDS'


    #- name: Deploy Docker Image
      #run: |
      #  docker run -d -p 8080:8000 ${{ secrets.DOCKER_HUB_USERNAME }}/my-fastapi-app:latest
      #env:
        #DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        #DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    #- name: Check Running Containers
      #run: |
        #docker ps
      #env:
        #DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        #DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

