name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.5
    - name: Clean project
      run: |
        find . -name "*.pyc" -exec rm -f {} \;
        rm -rf __pycache__
    - name: Clear Pycache
      run: find . -name "__pycache__" -exec rm -r {} +
    - name: Install Python Dependencies
      run: |
        python -m pip install -r requirements.txt --upgrade

    - name: Install pytest
      run: python -m pip install pytest
    
    #- name: Build Project
      #run: |
        #uvicorn main:app --reload --host 0.0.0.0 --port 8000

    #- name: Run Tests
      #run: |
        #pytest

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
      
    - name: Build Docker Image and Push it to Docker Hub
      run: |
        docker build -t my-fastapi-app:latest .
        echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker tag my-fastapi-app:latest ${{ secrets.DOCKER_HUB_USERNAME }}/my-fastapi-app:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-fastapi-app:latest